# Generated by Django 4.2.1 on 2023-05-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('identification_number', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_staff', to='tracker.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Staff',
                'verbose_name_plural': 'Company Staffs',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='tracker.company')),
            ],
            options={
                'verbose_name': 'Company Employee',
                'verbose_name_plural': 'Company Employees',
            },
        ),
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('checkout_condition', models.TextField()),
                ('return_condition', models.TextField()),
                ('allocated_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_by', to='tracker.companystaff')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_asset', to='tracker.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocated_employee', to='tracker.companyemployee')),
            ],
            options={
                'verbose_name': 'Asset Allocation',
                'verbose_name_plural': 'Asset Allocations',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_asset', to='tracker.company'),
        ),
    ]
