# Generated by Django 4.2.1 on 2023-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetallocation',
            name='checkout_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetallocation',
            name='return_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
